name: dockerhub-description

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/description.yml'
jobs:
  dockerhubdescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ronivay/xen-orchestra
